<a href="https://colab.research.google.com/github/WanpinCai/Machine-Learning-Algorithms-in-Python/blob/main/dara_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Preprocessing Tools**

**Importing the libraries**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**Importing the dataset**

In [ ]:
from re import X
dataset = pd.read_csv('Iris.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[1.00e+00 5.10e+00 3.50e+00 1.40e+00 2.00e-01]
 [2.00e+00 4.90e+00 3.00e+00 1.40e+00 2.00e-01]
 [3.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01]
 [4.00e+00 4.60e+00 3.10e+00 1.50e+00 2.00e-01]
 [5.00e+00 5.00e+00 3.60e+00 1.40e+00 2.00e-01]
 [6.00e+00 5.40e+00 3.90e+00 1.70e+00 4.00e-01]
 [7.00e+00 4.60e+00 3.40e+00 1.40e+00 3.00e-01]
 [8.00e+00 5.00e+00 3.40e+00 1.50e+00 2.00e-01]
 [9.00e+00 4.40e+00 2.90e+00 1.40e+00 2.00e-01]
 [1.00e+01 4.90e+00 3.10e+00 1.50e+00 1.00e-01]
 [1.10e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01]
 [1.20e+01 4.80e+00 3.40e+00 1.60e+00 2.00e-01]
 [1.30e+01 4.80e+00 3.00e+00 1.40e+00 1.00e-01]
 [1.40e+01 4.30e+00 3.00e+00 1.10e+00 1.00e-01]
 [1.50e+01 5.80e+00 4.00e+00 1.20e+00 2.00e-01]
 [1.60e+01 5.70e+00 4.40e+00 1.50e+00 4.00e-01]
 [1.70e+01 5.40e+00 3.90e+00 1.30e+00 4.00e-01]
 [1.80e+01 5.10e+00 3.50e+00 1.40e+00 3.00e-01]
 [1.90e+01 5.70e+00 3.80e+00 1.70e+00 3.00e-01]
 [2.00e+01 5.10e+00 3.80e+00 1.50e+00 3.00e-01]
 [2.10e+01 5.40e+00 3.40e+00 1.70e+00 2.

In [ ]:
print(y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

In [ ]:
print(type(X), type(y))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [ ]:
print(X.shape, y.shape)

(150, 5) (150,)


**Taking care of missing data**

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:4])
X[:, 1:4] = imputer.transform(X[:, 1:4])

In [ ]:
print(X)

[[1.00e+00 5.10e+00 3.50e+00 1.40e+00 2.00e-01]
 [2.00e+00 4.90e+00 3.00e+00 1.40e+00 2.00e-01]
 [3.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01]
 [4.00e+00 4.60e+00 3.10e+00 1.50e+00 2.00e-01]
 [5.00e+00 5.00e+00 3.60e+00 1.40e+00 2.00e-01]
 [6.00e+00 5.40e+00 3.90e+00 1.70e+00 4.00e-01]
 [7.00e+00 4.60e+00 3.40e+00 1.40e+00 3.00e-01]
 [8.00e+00 5.00e+00 3.40e+00 1.50e+00 2.00e-01]
 [9.00e+00 4.40e+00 2.90e+00 1.40e+00 2.00e-01]
 [1.00e+01 4.90e+00 3.10e+00 1.50e+00 1.00e-01]
 [1.10e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01]
 [1.20e+01 4.80e+00 3.40e+00 1.60e+00 2.00e-01]
 [1.30e+01 4.80e+00 3.00e+00 1.40e+00 1.00e-01]
 [1.40e+01 4.30e+00 3.00e+00 1.10e+00 1.00e-01]
 [1.50e+01 5.80e+00 4.00e+00 1.20e+00 2.00e-01]
 [1.60e+01 5.70e+00 4.40e+00 1.50e+00 4.00e-01]
 [1.70e+01 5.40e+00 3.90e+00 1.30e+00 4.00e-01]
 [1.80e+01 5.10e+00 3.50e+00 1.40e+00 3.00e-01]
 [1.90e+01 5.70e+00 3.80e+00 1.70e+00 3.00e-01]
 [2.00e+01 5.10e+00 3.80e+00 1.50e+00 3.00e-01]
 [2.10e+01 5.40e+00 3.40e+00 1.70e+00 2.

**Encoding categorical data**

**Encoding the Independent variable**

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

  (0, 0)	1.0
  (0, 150)	5.1
  (0, 151)	3.5
  (0, 152)	1.4
  (0, 153)	0.2
  (1, 1)	1.0
  (1, 150)	4.9
  (1, 151)	3.0
  (1, 152)	1.4
  (1, 153)	0.2
  (2, 2)	1.0
  (2, 150)	4.7
  (2, 151)	3.2
  (2, 152)	1.3
  (2, 153)	0.2
  (3, 3)	1.0
  (3, 150)	4.6
  (3, 151)	3.1
  (3, 152)	1.5
  (3, 153)	0.2
  (4, 4)	1.0
  (4, 150)	5.0
  (4, 151)	3.6
  (4, 152)	1.4
  (4, 153)	0.2
  :	:
  (145, 145)	1.0
  (145, 150)	6.7
  (145, 151)	3.0
  (145, 152)	5.2
  (145, 153)	2.3
  (146, 146)	1.0
  (146, 150)	6.3
  (146, 151)	2.5
  (146, 152)	5.0
  (146, 153)	1.9
  (147, 147)	1.0
  (147, 150)	6.5
  (147, 151)	3.0
  (147, 152)	5.2
  (147, 153)	2.0
  (148, 148)	1.0
  (148, 150)	6.2
  (148, 151)	3.4
  (148, 152)	5.4
  (148, 153)	2.3
  (149, 149)	1.0
  (149, 150)	5.9
  (149, 151)	3.0
  (149, 152)	5.1
  (149, 153)	1.8


**Encoding the Dependent Variable**

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


**Splitting the dataset into the Training set and Test set**

In [ ]:
print(X[:5])

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [ ]:
import numpy as np
# Attempt to unwrap any embedded object
if isinstance(X, np.ndarray) and X.dtype == 'object':
    X = X.item()  # This extracts the embedded object if `X` is an array holding an object


In [ ]:
print(X.shape)
print(X[:5])  # This should work if `X` is now a 2D array


(150, 154)
  (0, 0)	1.0
  (0, 150)	5.1
  (0, 151)	3.5
  (0, 152)	1.4
  (0, 153)	0.2
  (1, 1)	1.0
  (1, 150)	4.9
  (1, 151)	3.0
  (1, 152)	1.4
  (1, 153)	0.2
  (2, 2)	1.0
  (2, 150)	4.7
  (2, 151)	3.2
  (2, 152)	1.3
  (2, 153)	0.2
  (3, 3)	1.0
  (3, 150)	4.6
  (3, 151)	3.1
  (3, 152)	1.5
  (3, 153)	0.2
  (4, 4)	1.0
  (4, 150)	5.0
  (4, 151)	3.6
  (4, 152)	1.4
  (4, 153)	0.2


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_train)

  (0, 91)	1.0
  (0, 150)	6.1
  (0, 151)	3.0
  (0, 152)	4.6
  (0, 153)	1.4
  (1, 135)	1.0
  (1, 150)	7.7
  (1, 151)	3.0
  (1, 152)	6.1
  (1, 153)	2.3
  (2, 69)	1.0
  (2, 150)	5.6
  (2, 151)	2.5
  (2, 152)	3.9
  (2, 153)	1.1
  (3, 128)	1.0
  (3, 150)	6.4
  (3, 151)	2.8
  (3, 152)	5.6
  (3, 153)	2.1
  (4, 114)	1.0
  (4, 150)	5.8
  (4, 151)	2.8
  (4, 152)	5.1
  (4, 153)	2.4
  :	:
  (115, 133)	1.0
  (115, 150)	6.3
  (115, 151)	2.8
  (115, 152)	5.1
  (115, 153)	1.5
  (116, 137)	1.0
  (116, 150)	6.4
  (116, 151)	3.1
  (116, 152)	5.5
  (116, 153)	1.8
  (117, 72)	1.0
  (117, 150)	6.3
  (117, 151)	2.5
  (117, 152)	4.9
  (117, 153)	1.5
  (118, 140)	1.0
  (118, 150)	6.7
  (118, 151)	3.1
  (118, 152)	5.6
  (118, 153)	2.4
  (119, 37)	1.0
  (119, 150)	4.9
  (119, 151)	3.1
  (119, 152)	1.5
  (119, 153)	0.1


In [ ]:
print(X_test)

  (0, 14)	1.0
  (0, 150)	5.8
  (0, 151)	4.0
  (0, 152)	1.2
  (0, 153)	0.2
  (1, 98)	1.0
  (1, 150)	5.1
  (1, 151)	2.5
  (1, 152)	3.0
  (1, 153)	1.1
  (2, 75)	1.0
  (2, 150)	6.6
  (2, 151)	3.0
  (2, 152)	4.4
  (2, 153)	1.4
  (3, 16)	1.0
  (3, 150)	5.4
  (3, 151)	3.9
  (3, 152)	1.3
  (3, 153)	0.4
  (4, 131)	1.0
  (4, 150)	7.9
  (4, 151)	3.8
  (4, 152)	6.4
  (4, 153)	2.0
  :	:
  (25, 99)	1.0
  (25, 150)	5.7
  (25, 151)	2.8
  (25, 152)	4.1
  (25, 153)	1.3
  (26, 33)	1.0
  (26, 150)	5.5
  (26, 151)	4.2
  (26, 152)	1.4
  (26, 153)	0.2
  (27, 19)	1.0
  (27, 150)	5.1
  (27, 151)	3.8
  (27, 152)	1.5
  (27, 153)	0.3
  (28, 73)	1.0
  (28, 150)	6.1
  (28, 151)	2.8
  (28, 152)	4.7
  (28, 153)	1.2
  (29, 146)	1.0
  (29, 150)	6.3
  (29, 151)	2.5
  (29, 152)	5.0
  (29, 153)	1.9


In [ ]:
print(y_train)

[1 2 1 2 2 0 1 0 1 2 2 0 2 2 1 2 0 0 0 1 0 0 2 2 2 2 2 1 2 1 0 2 2 0 0 2 0
 2 2 1 1 2 2 0 1 1 2 1 2 1 0 0 0 2 0 1 2 2 0 0 1 0 2 1 2 2 1 2 2 1 0 1 0 1
 1 0 1 0 0 2 2 2 0 0 1 0 2 0 2 2 0 2 0 1 0 1 1 0 0 1 0 1 1 0 1 1 1 1 2 0 0
 2 1 2 1 2 2 1 2 0]


In [ ]:
print(y_test)

[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 1 0 2 1 0 0 1 2]


**Featrue Scaling**

In [ ]:
X_train = X_train.toarray()
X_test = X_test.toarray()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [ ]:
print(X_train)

[[ 0.          0.          0.         ... -0.03612186  0.44748582
   0.2345312 ]
 [ 0.          0.          0.         ... -0.03612186  1.29803965
   1.39642889]
 [ 0.          0.          0.         ... -1.240184    0.0505607
  -0.15276803]
 ...
 [ 0.          0.          0.         ... -1.240184    0.61759659
   0.36363094]
 [ 0.          0.          0.         ...  0.20469056  1.01452171
   1.52552864]
 [ 0.          0.          0.         ...  0.20469056 -1.31032543
  -1.44376547]]


In [ ]:
print(X_test)

[[ 0.          0.          0.         ...  2.3720024  -1.48043619
  -1.31466572]
 [ 0.          0.          0.         ... -1.240184   -0.4597716
  -0.15276803]
 [ 0.          0.          0.         ... -0.03612186  0.33407864
   0.2345312 ]
 ...
 [ 0.          0.          0.         ...  1.89037755 -1.31032543
  -1.18556598]
 [ 0.          0.          0.         ... -0.51774672  0.50418941
  -0.02366829]
 [ 0.          0.          0.         ... -1.240184    0.67430017
   0.88002992]]
